name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  sast:
    name: SAST - Semgrep
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto .